version: 2.0
jobs:
    prod-deploy:
        docker:
            - image: circleci/node:7.10
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test
workflows:
    version: 2
    productionflow:
        jobs:
            - prod-deploy:
                context: heroku
                filters:
                    branches:
                        only:
                            - master
